#开发环境
#日志配置
log:
  level: INFO
  path: /data/sso_logs

#mybatis:
#  configLocation: classpath:config/mybatis/mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tw-sso?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  devtools:
    restart:
      enabled: true

server:
  port: 8081
  context-path: /
  
sso:
  sys:
    #登录地址,子应用可以自定义登录页面
    loginUrl: http://localhost:8081/login.jsp
    setCookieUrl: http://localhost:8081/setcookie
    #登录成功后跳转的地址
    successUrl: http://localhost:8081/